### ISSUE TITLE
En que url debo enviar los datos?

### ISSUE THREAD

**Issue by ghost** [eusonlito/redsys-Fake#1]
Estoy configurando redsys-fake con la otra classe de redsys pero no se a que archivo o url enviar los datos.
He instalado en un dominio aparte el redsys-fake. cuando entro mediante url http://www.fake-redsys.com/public/ me sale este error: URL "/public/" is not valid

Gracias 
![captura](https://cloud.githubusercontent.com/assets/9554816/10275974/3ba9282c-6b4c-11e5-9c90-5d36d8f3fd13.JPG)

**Comment by eusonlito** [comment]
Debes enviar la solicitud a una url que sería la misma que a la entidad bancaria, en este caso a `http://www.fake-redsys.com/public/realizarPago`.

**Comment by ghost** [comment]
Gracias. Funciona perfectamente. Agradezco el trabajo que has hecho para otros Developers.

Gracias
