### ISSUE TITLE
Estará disponible la nueva versión?

### ISSUE THREAD

**Issue by ghost** [eusonlito/redsys-Fake#2]
Hola, Habrá nueva actualización (Redsys SHA 256) ?
Gracias

**Comment by eusonlito** [comment]
Sí, después del estrés para sacar la versión cliente, ahora me tengo que poner con la de servidor :)

**Comment by ghost** [comment]
:+1:  Muchas gracias. Agradezco tu trabajo.

**Comment by ghost** [comment]
Hola, 
¿Cuando estará disponible más o menos? 
Gracias

**Comment by danielozano** [comment]
Tengo un medio fix que estoy utilizando para testear con Magento para sha256 a partir de un fork de tu proyecto. Lo he hecho muy rápido y a lo loco, y no lo he testado al 100% ni con otras plataformas:

https://github.com/danielozano/redsys-Fake

Quizás os sirva para algo.

**Comment by jromero-onclick** [comment]
Hola eusonlito hay versión nueva que funcione con SHA 256?

Gracias

**Comment by eusonlito** [comment]
Hola, lo siento mucho pero no creo que pueda obtener tiempo para este proyecto por el momento. Estoy en un momento de mucho trabajo y no me es posible actualizar esta librería.

**Comment by jromero-onclick** [comment]
@eusonlito sabes los cambios que se deberían hacer para funcionar en SHA256? O al menos una idea... Quizá podamos colaborar entre todos!

**Comment by eusonlito** [comment]
Hola, por si aún estais pensando en utilizar este servidor de pruebas, @marcbe se ha currado la implementación a SHA256. Tengo que probarlo, pero como comienzo no está nada mal.

Saludos!
