### ISSUE TITLE
Versión dockerizada

### ISSUE THREAD

**Issue by bernatvadell** [eusonlito/redsys-Fake#7]
Hola @eusonlito 

Sería posible integrar una versión dockerizada del proyecto?

Actualmente tengo varios proyectos integrados con redsys y siempre que hago algún cambio que afecta a la pasarela de pago me vuelvo loco para probar. 

Estaba buscando un redsys emulator y he encontrado tu servicio que parece que se puede ajustar a lo que necesito.

Para mis proyectos utilizo docker-compose para gestionar las dependencias, sería fantástico disponer de un servicio más que permitiría emular la pasarela.

En cualquier caso voy a probar tu servicio e intentaré hacer un PR con el Dockerfile

Gracias!

**Comment by keldrox** [comment]
Buenas @bernatvadell 

En mis proyectos me pasa exactamente igual cada vez que toco algo de la parte del checkout al hacer pruebas me vuelvo loco, ademas redsys da las credenciales para test y url al principio pero una vez integrada esa url test es eliminada...

Así que buscando os he encontrado, ¿que tal va esta librería? cual es su opinión @bernatvadell? 

Muchas gracias!

Saludos!

**Comment by bernatvadell** [comment]
Hola @keldrox 

Perfecto en mi caso!

Acabo de crear el PR que permite ejecutar redsys-fake como un contenedor docker, puedes ver el pr:

https://github.com/eusonlito/redsys-Fake/pull/8

en resumen, si tienes docker instalado, te puedes clonar el proyecto y ejecutar estos comandos (están en el readme)

Ejecuta la compilación de la imagen:
```bash
docker build -t redsys-fake .
```

Arranca el contenedor:
```bash
docker run -p 8000:80 -e KEY=sq7HjrUOBfKmC576ILgskD5srU870gJ7 redsys-fake
```

Si @eusonlito le interesa, podría publicar la imagen en el dockerhub y así únicamente haría falta utilizar el último comando

**Comment by eusonlito** [comment]
@bernatvadell para publicar en dockerhub necesitas algo de mí? Por mí no hay ningún problema que lo publiques bajo tu cuenta.

**Comment by bernatvadell** [comment]
Hola!

En principio no, si te parece bien, añademe como colaborador y configuro
una action en github para que lance automáticamente la generación de la
imagen y la envíe al dockerhub cada vez que se haga un cambio en el repo.

Gracias

**Comment by bernatvadell** [comment]
Listo! he publicado la imagen docker.

Ahora es suficiente con el docker run con la imagen publicada:

```bash
docker run -p 8000:80 -e KEY=sq7HjrUOBfKmC576ILgskD5srU870gJ7 bernatvadell/redsys-fake
```

Te lanzo el PR con la actualización del README
